name: Run Test UI

on: [ push ]

jobs:
  run_api_automation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install chrome
        uses: browser-actions/setup-chrome@v0.0.0
          
#      - name: Install Chrome
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y wget gnupg
#          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
#          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
#          sudo apt-get update
#          sudo apt-get install -y google-chrome-stable
#
#      - name: Install ChromeDriver
#        run: |
#          CHROME_DRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`
#          wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
#          unzip chromedriver_linux64.zip -d $HOME/bin
#          rm chromedriver_linux64.zip
#          sudo mv -f $HOME/bin/chromedriver /usr/local/bin/chromedriver
#          sudo chmod +x /usr/local/bin/chromedriver

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run with pytest
        if: always()
        run: pytest -v
